// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBJUVT1unsbKDE8e9LywzeRbfpTHejznM',
    appId: '1:801811172563:web:3d3b99b7506be0f7ecd826',
    messagingSenderId: '801811172563',
    projectId: 'tienda-shigidio',
    authDomain: 'tienda-shigidio.firebaseapp.com',
    storageBucket: 'tienda-shigidio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQjGHhWrShzWZCDS3VB-0jWCzoyvrwC3k',
    appId: '1:801811172563:ios:43addfd71a24e17becd826',
    messagingSenderId: '801811172563',
    projectId: 'tienda-shigidio',
    storageBucket: 'tienda-shigidio.appspot.com',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQjGHhWrShzWZCDS3VB-0jWCzoyvrwC3k',
    appId: '1:801811172563:ios:43addfd71a24e17becd826',
    messagingSenderId: '801811172563',
    projectId: 'tienda-shigidio',
    storageBucket: 'tienda-shigidio.appspot.com',
    iosBundleId: 'com.example.shoppingListApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBJUVT1unsbKDE8e9LywzeRbfpTHejznM',
    appId: '1:801811172563:web:5d5b1122f8901fddecd826',
    messagingSenderId: '801811172563',
    projectId: 'tienda-shigidio',
    authDomain: 'tienda-shigidio.firebaseapp.com',
    storageBucket: 'tienda-shigidio.appspot.com',
  );
}
